### PR TITLE
Fix panic when subresources is not initiated

### PR DESCRIPTION
**Pull request by taraktikos**

### CODE REVIEW

**Comment by taraktikos** [comment]
close #91

**Comment by santhosh-tekuri** [comment]
thanks for the issue and the fix.

could you please add test case to one of subfolders of `testdata/tests`

also change the commit message to `fix: panic when resource.subresources is not initiated` to follow project conventions

**Comment by taraktikos** [comment]
@santhosh-tekuri thanks for the feedback. I will add

**Comment by santhosh-tekuri** [comment]
actually r.subresources should be used only for root resource (as commented in struct)
for each root resource, fillSubschemas is always called which initialises sub resource.
also resolveFragment must be called on root resource. 

thus sub resources should have been initialised there. so I want check why this is happening by using your test case.
may be the bug could be something else(such as resolveFragment getting called non root resource)

**Comment by taraktikos** [comment]
Unfortunately, I can't find a schema to reproduce this behavior. Only that stack trace

**Comment by santhosh-tekuri** [comment]
Not reproducable

**Comment by DerkSchooltink** [comment]
This seems to be an issue when a reference is loaded which has a "type" property:

schema:
```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "$ref": "definitions.json#/type"
    }
  }
}
```

definitions.json:

```
{
  "type": {
    "type": "string",
    "enum": [
      "1",
      "2"
    ]
  }
}
```

Seems to consistently result into panics at:

`r.subresources[floc] = res`

I'm not that well-read into this code, but at least I can reproduce it. Oh, and assigning an empty map to subresources does fix the panics, but it will fail to validate with the following error:

```jsonschema file:///<redacted>.json compilation failed: '/type' does not validate with https://json-schema.org/draft/2019-09/schema#/allOf/2/$ref/properties/type/anyOf/0/$ref/enum: value must be one of "array", "boolean", "integer", "null", "number", "object", "string"] ```

If I rename `type` to something like `config_type`, the error is gone (as well as the panic).

Would love to get your input @santhosh-tekuri

**Comment by santhosh-tekuri** [comment]
@DerkSchooltink I do not get panic with your example. here is playground link for your example: https://go.dev/play/p/G9GgLYPY_8G

you only get a compilation error (not panic); the compilation error is expected since `definitions.json` is not a valid schema

**Comment by DerkSchooltink** [comment]
Hmm, I stripped some properties for privacy reasons, I will attempt to give a minimal example after the weekend 👌

**Pull request closed without merging**
